# run tests on github actions on pull request against master
name: Test on PR
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.13.0'
      - run: npm ci
      - run: npm test


